//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using com.shephertz.app42.paas.sdk.csharp;
using com.shephertz.app42.paas.sdk.csharp.game;
using System.Collections.Generic;

public class FriendsLeaderBoardCallBack : App42CallBack {
	
	public static string fbUserName = "";
	public static string fbUserProfilePic = "";
	public static string fbUserId = "";
	public static bool isConnected = false;
	
	public static bool fromSaveScore = false;
	public static bool fromLeaderBoard = false;
	
	
	public static Dictionary<string,object> metaInfo = new Dictionary<string,object>();
	public static Dictionary<string,object> nameAndPP = new Dictionary<string,object>();
	
	
	public static IList<object> friendList = new List<object> ();
	
	//private string result = "";
	
//	AppController fbUserCon = new AppController ();
	
	//public static string fbAccessToken = "";
	
	public void OnSuccess (object response)
	{

		
		if (response is Game){
			Game gameObj = (Game)response;
			Debug.Log("Game ::: "+gameObj.ToString());
				if(gameObj.GetScoreList().Count > 0){
					for (int i=0; i<gameObj.GetScoreList().Count; i++){
						string name = gameObj.GetScoreList()[i].GetFacebookProfile().GetName();
						string score = gameObj.GetScoreList()[i].GetValue().ToString();
						string profilePic = gameObj.GetScoreList()[i].GetFacebookProfile().GetPicture();
						string userId = gameObj.GetScoreList()[i].GetFacebookProfile().GetName();
						
						Texture.GetInstance().ExecuteShow(userId, profilePic);
					
						IList<string> slist1 = new List<string>();
						slist1.Add(userId);
						slist1.Add(name);
						slist1.Add(profilePic);
						slist1.Add(score);
						friendList.Add(slist1);
					}
				}
			}

	}
	public void OnException (Exception exception)
	{
		Debug.Log("Exception :: "+exception.ToString());

	}
	
	
	public static IList<object> GetList(){
		return friendList;
	}
	
}


